// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package repo

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	CreateCategory(ctx context.Context, arg CreateCategoryParams) (Category, error)
	CreateTransaction(ctx context.Context, arg CreateTransactionParams) (Transaction, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (CreateUserRow, error)
	DeleteCategory(ctx context.Context, arg DeleteCategoryParams) (int64, error)
	DeleteTransaction(ctx context.Context, arg DeleteTransactionParams) (int64, error)
	FindCategoryByID(ctx context.Context, arg FindCategoryByIDParams) (Category, error)
	FindTransactionByID(ctx context.Context, arg FindTransactionByIDParams) (FindTransactionByIDRow, error)
	FindUserByEmail(ctx context.Context, email string) (User, error)
	FindUserByID(ctx context.Context, id pgtype.UUID) (FindUserByIDRow, error)
	GetMonthlySummary(ctx context.Context, userID pgtype.UUID) ([]GetMonthlySummaryRow, error)
	GetTransactionSummary(ctx context.Context, userID pgtype.UUID) (GetTransactionSummaryRow, error)
	ListCategoriesByUser(ctx context.Context, userID pgtype.UUID) ([]Category, error)
	ListTransactionsByUser(ctx context.Context, userID pgtype.UUID) ([]ListTransactionsByUserRow, error)
	UpdateCategory(ctx context.Context, arg UpdateCategoryParams) (Category, error)
	UpdateTransaction(ctx context.Context, arg UpdateTransactionParams) (Transaction, error)
}

var _ Querier = (*Queries)(nil)
