// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: transaction.sql

package repo

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createTransaction = `-- name: CreateTransaction :one
INSERT INTO transactions (
    user_id,
    category_id,
    amount_cents,
    note,
    transaction_date
)
VALUES (
    $1, $2, $3, $4, $5
)
RETURNING
    id,
    user_id,
    category_id,
    amount_cents,
    note,
    transaction_date,
    created_at,
    updated_at
`

type CreateTransactionParams struct {
	UserID          pgtype.UUID `json:"user_id"`
	CategoryID      pgtype.UUID `json:"category_id"`
	AmountCents     int64       `json:"amount_cents"`
	Note            pgtype.Text `json:"note"`
	TransactionDate pgtype.Date `json:"transaction_date"`
}

func (q *Queries) CreateTransaction(ctx context.Context, arg CreateTransactionParams) (Transaction, error) {
	row := q.db.QueryRow(ctx, createTransaction,
		arg.UserID,
		arg.CategoryID,
		arg.AmountCents,
		arg.Note,
		arg.TransactionDate,
	)
	var i Transaction
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.CategoryID,
		&i.AmountCents,
		&i.Note,
		&i.TransactionDate,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteTransaction = `-- name: DeleteTransaction :execrows
DELETE FROM transactions
WHERE id = $1
  AND user_id = $2
`

type DeleteTransactionParams struct {
	ID     pgtype.UUID `json:"id"`
	UserID pgtype.UUID `json:"user_id"`
}

func (q *Queries) DeleteTransaction(ctx context.Context, arg DeleteTransactionParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteTransaction, arg.ID, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const findTransactionByID = `-- name: FindTransactionByID :one
SELECT
    t.id,
    t.user_id,
    t.category_id,
    c.name AS category_name,
    t.amount_cents,
    t.note,
    t.transaction_date,
    t.created_at
FROM transactions t
JOIN categories c ON c.id = t.category_id
WHERE t.id = $1
  AND t.user_id = $2
`

type FindTransactionByIDParams struct {
	ID     pgtype.UUID `json:"id"`
	UserID pgtype.UUID `json:"user_id"`
}

type FindTransactionByIDRow struct {
	ID              pgtype.UUID        `json:"id"`
	UserID          pgtype.UUID        `json:"user_id"`
	CategoryID      pgtype.UUID        `json:"category_id"`
	CategoryName    string             `json:"category_name"`
	AmountCents     int64              `json:"amount_cents"`
	Note            pgtype.Text        `json:"note"`
	TransactionDate pgtype.Date        `json:"transaction_date"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) FindTransactionByID(ctx context.Context, arg FindTransactionByIDParams) (FindTransactionByIDRow, error) {
	row := q.db.QueryRow(ctx, findTransactionByID, arg.ID, arg.UserID)
	var i FindTransactionByIDRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.CategoryID,
		&i.CategoryName,
		&i.AmountCents,
		&i.Note,
		&i.TransactionDate,
		&i.CreatedAt,
	)
	return i, err
}

const getMonthlySummary = `-- name: GetMonthlySummary :many
SELECT
    DATE_TRUNC('month', transaction_date) AS month,
    SUM(CASE WHEN type = 'income' THEN amount_cents ELSE 0 END) AS total_income,
    SUM(CASE WHEN type = 'expense' THEN amount_cents ELSE 0 END) AS total_expense
FROM transactions
WHERE user_id = $1
GROUP BY month
ORDER BY month DESC
`

type GetMonthlySummaryRow struct {
	Month        pgtype.Interval `json:"month"`
	TotalIncome  int64           `json:"total_income"`
	TotalExpense int64           `json:"total_expense"`
}

func (q *Queries) GetMonthlySummary(ctx context.Context, userID pgtype.UUID) ([]GetMonthlySummaryRow, error) {
	rows, err := q.db.Query(ctx, getMonthlySummary, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetMonthlySummaryRow
	for rows.Next() {
		var i GetMonthlySummaryRow
		if err := rows.Scan(&i.Month, &i.TotalIncome, &i.TotalExpense); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTransactionSummary = `-- name: GetTransactionSummary :one
SELECT
    COALESCE(SUM(CASE WHEN type = 'income' THEN amount_cents ELSE 0 END), 0) AS total_income,
    COALESCE(SUM(CASE WHEN type = 'expense' THEN amount_cents ELSE 0 END), 0) AS total_expense
FROM transactions
WHERE user_id = $1
`

type GetTransactionSummaryRow struct {
	TotalIncome  interface{} `json:"total_income"`
	TotalExpense interface{} `json:"total_expense"`
}

func (q *Queries) GetTransactionSummary(ctx context.Context, userID pgtype.UUID) (GetTransactionSummaryRow, error) {
	row := q.db.QueryRow(ctx, getTransactionSummary, userID)
	var i GetTransactionSummaryRow
	err := row.Scan(&i.TotalIncome, &i.TotalExpense)
	return i, err
}

const listTransactionsByUser = `-- name: ListTransactionsByUser :many
SELECT
    t.id,
    t.user_id,
    t.category_id,
    c.name AS category_name,
    t.amount_cents,
    t.note,
    t.transaction_date,
    t.created_at
FROM transactions t
JOIN categories c ON c.id = t.category_id
WHERE t.user_id = $1
ORDER BY t.transaction_date DESC
`

type ListTransactionsByUserRow struct {
	ID              pgtype.UUID        `json:"id"`
	UserID          pgtype.UUID        `json:"user_id"`
	CategoryID      pgtype.UUID        `json:"category_id"`
	CategoryName    string             `json:"category_name"`
	AmountCents     int64              `json:"amount_cents"`
	Note            pgtype.Text        `json:"note"`
	TransactionDate pgtype.Date        `json:"transaction_date"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) ListTransactionsByUser(ctx context.Context, userID pgtype.UUID) ([]ListTransactionsByUserRow, error) {
	rows, err := q.db.Query(ctx, listTransactionsByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListTransactionsByUserRow
	for rows.Next() {
		var i ListTransactionsByUserRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.CategoryID,
			&i.CategoryName,
			&i.AmountCents,
			&i.Note,
			&i.TransactionDate,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
